version: '3.6'

networks:
  mongodb-nt:
    name: $NETWORK

services:
  mongo:
    image: mongo:$TAG
    restart: always
    container_name: $CONTAINER
    environment:
      - TZ=$TIMEZONE
      - MONGO_INITDB_ROOT_USERNAME=$ROOTUSER
      - MONGO_INITDB_ROOT_PASSWORD=$ROOTPASSWD
      - MONGO_INITDB_DATABASE=$DBDEV
    volumes:
      - $PWD/data:/data/db
      - ./db-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongodb-nt
    ports:
      - $PORT:27017
